export const moviesConstants = {
  GET_MOVIES: 'GET_MOVIES',
  RESET_MOVIE: 'RESET_MOVIE',
  NEXT_PAGE: 'NEXT_PAGE',
  GET_COMMENTS: 'GET_COMMENTS',
  ADD_COMMENT: 'ADD_COMMENT',
  BACK_MOVIES: 'BACK_MOVIES',
  GET_SEARCH: 'GET_SEARCH',
  GET_QUERY: 'GET_QUERY'
};